cleaned up logging, fixed init and clean process

diff --git a/add b/add
--- a/add
+++ b/add
@@ -1,109 +1,163 @@
 #!/usr/bin/env bash
-# add.sh
+# add
 # adds a DS key to the parent domain when there are no CDS keys present.  If this is a clean run (i.e. no keys, service named start, make a cup of tea, then run this run this on each domain from the root down.)
 # e.g. $ add.sh example.com
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-# shellcheck disable=1091
-. /etc/cme/dnssec-monitor.env
-# shellcheck disable=1091
-. "${DIR}/lib.sh"
-log "update DEBUG pre param set 1:$1 2:$2 3:$3"
-log "update DEBUG pre param set DOMAIN:$DOMAIN KEY_ID:$KEY_ID VIEW:$VIEW"
-DOMAIN=${DOMAIN:-$1}
-KEY_ID=${KEY_ID:-$2}
-VIEW=${VIEW:-$3}
-log "update DEBUG post param set DOMAIN:$DOMAIN KEY_ID:$KEY_ID VIEW:$VIEW"
 
-PARENT_DOMAIN=$(parent_domain "${DOMAIN}")
-TTL=60
+if [[ $# -lt 6 || $# -gt 6 ]]; then
+  echo -e
+  echo "cme-dnssec-monitor/add v0.1.0 - adds a new DS key to the zone"
+  echo "$@"
+  echo -e
+  echo "Usage:"
+  echo -e
+  echo "  ENV VARS - declare/export these env values and pass \"\" as an empty parameter
 
-log "adding KSK for ${DOMAIN}"
-#find the id for the currently active KSK for the provided domain
-for f in "${KEY_PATH}/K${DOMAIN}.+014+"*.state; do
-  if grep -q "KSK: yes" "$f"; then
+  declare -x DOMAIN=\"example.com\"
+  declare -x VIEW=\"externals-master\"
+  declare -x IP_ADDR=\"127.0.0.1\"
+  declare -x NS_SERVER=\"192.68.0.2\"
+  declare -x TTL=60
+  declare -x KEY_ID=01234
+  declare -x KEY_PATH=/var/cache/bind/keys
+  declare -x DSPROCESS_PATH=/tmp/cme/dsprocess
+"
+  echo -e
+  echo "  examples:"
+  echo "  $ add \$domain \$view \$ip_addr \$ns_server \$ttl \$key_id"
+  echo -e
+  echo "  $ TTL=60"
+  echo "  $ add test.example.com externals-master 10.0.254.2 192.168.88.2 "" 01234"
+  exit 1
+fi
+
+if [[ -f "/etc/cme/dnssec-monitor.env" ]]; then
+  echo "...loading /etc/cme/dnssec-monitor.env"
+  # shellcheck disable=SC1091
+  . "/etc/cme/dnssec-monitor.env"
+fi
+
+if [[ -f "${DIR}/lib.sh" ]]; then
+  # shellcheck disable=SC1091
+  echo "...loading lib ${DIR}/lib.sh"
+  . "${DIR}/lib.sh"
+fi
+
+declare domain=${DOMAIN:-$1}
+declare view=${VIEW:-$2}
+declare ip_addr=${IP_ADDR:-$3}
+declare ns_server=${NS_SERVER:-$4}
+declare ttl=${TTL:-$5}
+declare key_id=${KEY_ID:-$6}
+declare key_path=${KEY_PATH:-${DATA_PATH}/keys}
+declare dsprocess_path=${DSPROCESS_PATH:-/tmp/cme/dsprocess}
+declare domain_key=/etc/bind/rndc.${view}.key
+declare domain_conf=/etc/bind/rndc.${view}.conf
+declare domain_parent
+declare record
+
+domain_parent=$(parent_domain ${domain})
+render_params
+
+prepare_domain
+
+log "adding KSK for ${domain}"
+
+if [[ ! -d "${dsprocess_path}/${view}" ]]; then
+  mkdir "${dsprocess_path}/${view}"
+fi
+chown root:root "${dsprocess_path}/${view}"
+chmod 770
+
+# find the id for the currently active KSK for the provided domain
+declare found_key=false
+for f in "${key_path}/${view}/K${domain}.+014+"*.state; do
+  if grep -q "KSK: ${domain_conf}yes" "$f"; then
     if ! grep -q "Successor:" "$f"; then
       id=$(echo "$f" | grep -Po '\d+' | tail -n 1)
+      log "found KSK key: $f"
+      found_key=true
     fi
   fi
 done
+if [[ $found_key == "true" ]];then
+  log "could not locate KSK state: $key_id in ${view}"
+  exit 1
+fi
+
 f=${f/\.state/\.key}
-log "handling KSK publish - running nsupdate ${DOMAIN}"
+log "handling KSK publish - running nsupdate ${domain}"
 
-# shellcheck disable=SC2068
-view_var="${VIEW^^}"
-view_var="${view_var//-/_}"
-iface_var=${view_var}_IFACE
-key_var=${view_var}_KEY_NAME
-log "key_var: $key_var"
-key_name="${!key_var}"
-key_name_var="${key_name^^}"
-key_name_var="${key_name_var//-/_}"
-ip_addr="${!iface_var}"
-key_file="${CONF_PATH}/rndc.${VIEW}.key"
-
-if [[ ! -f "${CONF_PATH}/rndc.${VIEW}.key" ]]; then
-  log "rndc key file not found at ${CONF_PATH}/rndc.${VIEW}.key"
-  exit 0
+if [[ ! -f "${domain_key}" ]]; then
+  log "rndc key file not found: ${domain_key}"
+  exit 1
 fi
 
-if [[ ! -f "${KEY_PATH}/${VIEW}/K${DOMAIN}.+014+${KEY_ID}.key" ]]; then
-  log "key file ${KEY_PATH}/${VIEW}/K${DOMAIN}.+014+${KEY_ID}.key NOT found! Aborting."
-  exit 0
+if [[ ! -f "${key_path}/${view}/K${domain}.+014+${KEY_ID}.key" ]]; then
+  log "KSK key  NOT found! Aborting: ${key_path}/${view}/K${domain}.+014+${KEY_ID}.key"
+  exit 1
 fi
-
-log "view ................... : ${VIEW}"
-log "domain ................. : ${DOMAIN}"
-log "key_id ................. : ${KEY_ID}"
-log "key_var ................ : ${!key_var}"
-log "ip_addr ................ : ${ip_addr}"
-log "key_name ............... : ${key_name}"
-log "key_file ................: ${key_file}"
-log "TTL .................... : $TTL"
 
 #check to see if we have a CDS key published
-ds=$(dig -b "$ip_addr" "@${NS_SERVER}" +noall +answer "$DOMAIN" DS)
+ds=$(dig -b "$ip_addr" "@${NS_SERVER}" +noall +answer "$domain" DS)
 if [[ $ds == "" ]]; then
-  log "no DS published for ${DOMAIN}/${VIEW}"
+  log "no DS published for ${domain}/${view}"
 fi
 
-ds=$(dig -b "$ip_addr" "@${NS_SERVER}" +noall +answer "$DOMAIN" CDS)
-if [[ $ds == "" ]]; then
-  log "no CDS published for ${DOMAIN}/${VIEW}"
+cds=$(dig -b "$ip_addr" "@${NS_SERVER}" +noall +answer "$domain" CDS)
+if [[ $cds == "" ]]; then
+  log "no CDS published for ${domain}/${view}"
 fi
 
-ds=$(dnssec-dsfromkey -a SHA-384 "${KEY_PATH}/${VIEW}/K${DOMAIN}.+014+${KEY_ID}.key" | awk '{print $4" "$5" "$6" "$7}')
+ds=$(dnssec-dsfromkey -a SHA-384 "${key_path}/${view}/K${domain}.+014+${KEY_ID}.key" | awk '{print $4" "$5" "$6" "$7}')
 log "DS:$ds"
 
-rndc -k "${CONF_PATH}/rndc.${VIEW}.key" -c "${CONF_PATH}/rndc.${VIEW}.conf" thaw ${PARENT_DOMAIN} in ${VIEW}
+rndc -k "${domain_key}" -c "${domain_conf}" thaw ${domain_parent} in ${view}
 
 # if [[ $CME_DNSSEC_MONITOR_DEBUG -eq 1 ]]; then
 log "$(
   cat <<EOF
-nsupdate -k "${CONF_PATH}/rndc.${VIEW}.key"
+nsupdate -k "${domain_key}"
 server ${NS_SERVER}
-zone ${PARENT_DOMAIN}. in ${VIEW}
-add ${DOMAIN}. ${TTL} DS $ds
+zone ${domain_parent}. in ${view}
+add ${domain}. ${TTL} DS $ds
 send
 EOF
 )"
 # fi
 
-nsupdate -l "${ip_addr}" -k "${CONF_PATH}/rndc.${VIEW}.key" < <(
+nsupdate -l "${ip_addr}" -k "${domain_key}" < <(
   cat <<EOF
 server ${NS_SERVER}
-zone ${PARENT_DOMAIN}. in ${VIEW}
-add ${DOMAIN}. ${TTL} DS $ds
+zone ${domain_parent}. in ${view}
+add ${domain}. ${TTL} DS $ds
 send
 EOF
 )
 
-rndc -k "${CONF_PATH}/rndc.${VIEW}.key" -c "${CONF_PATH}/rndc.${VIEW}.conf" freeze ${PARENT_DOMAIN} in ${VIEW}
-rndc -k "${CONF_PATH}/rndc.${VIEW}.key" -c "${CONF_PATH}/rndc.${VIEW}.conf" sync -clean ${PARENT_DOMAIN} in ${VIEW}
+    log "$(success_icon $?)...flushing ${domain_parent}"
+    rndc -c ${domain_conf} -k ${domain_key} -s "${ns_server}" flush ${view}
 
-log "rndc -k \"${CONF_PATH}/rndc.${VIEW}.key\" -c \"${CONF_PATH}/rndc.${VIEW}.conf\" notify ${PARENT_DOMAIN} in ${VIEW}"
-rndc -k "${CONF_PATH}/rndc.${VIEW}.key" -c "${CONF_PATH}/rndc.${VIEW}.conf" notify ${PARENT_DOMAIN} in ${VIEW}
-log "rndc -k \"${CONF_PATH}/rndc.${VIEW}.key\" -c \"${CONF_PATH}/rndc.${VIEW}.conf\" notify ${DOMAIN} in ${VIEW}"
-rndc -k "${CONF_PATH}/rndc.${VIEW}.key" -c "${CONF_PATH}/rndc.${VIEW}.conf" notify ${DOMAIN} in ${VIEW}
+    log "$(success_icon $?)...syncing"
+    rndc -c ${domain_conf} -k ${domain_key} -s "${ns_server}" sync -clean
 
-dig -b "${ip_addr}" "@${NS_SERVER}" +norecurse "${DOMAIN}". DNSKEY | dnssec-dsfromkey -a SHA-384 -f - "${DOMAIN}" | tee "${DSPROCESS_PATH}/${VIEW}/dsset-${DOMAIN}." >/dev/null
-dig -b "${ip_addr}" "@${NS_SERVER}" +dnssec +noall +answer "${DOMAIN}" DNSKEY "${DOMAIN}" CDNSKEY "${DOMAIN}" CDS | tee "${DSPROCESS_PATH}/${VIEW}/file-${DOMAIN}" >/dev/null
+    log "$(success_icon $?)...notifying ${domain}"
+    rndc -c ${domain_conf} -k ${domain_key} notify "${domain}" IN "${view}"
+
+    log "$(success_icon $?)...notifying ${domain_parent}"
+    rndc -c ${domain_conf} -k ${domain_key} notify "${domain_parent}" IN "${view}"
+  done
+
+rndc -k "${domain_key}" -c "${domain_conf}" freeze ${domain_parent} in ${view}
+
+rndc -k "${domain_key}" -c "${domain_conf}" sync -clean ${domain_parent} in ${view}
+
+log "rndc -k \"${domain_key}\" -c \"${domain_conf}\" notify ${domain_parent} in ${view}"
+rndc -k "${domain_key}" -c "${domain_conf}" notify ${domain_parent} in ${view}
+log "rndc -k \"${domain_key}\" -c \"${domain_conf}\" notify ${domain} in ${view}"
+rndc -k "${domain_key}" -c "${domain_conf}" notify ${domain} in ${view}
+
+dig -b "${ip_addr}" "@${NS_SERVER}" +norecurse "${domain}". DNSKEY | dnssec-dsfromkey -a SHA-384 -f - "${domain}" | tee "${DSPROCESS_PATH}/${view}/dsset-${domain}." >/dev/null
+dig -b "${ip_addr}" "@${NS_SERVER}" +dnssec +noall +answer "${domain}" DNSKEY "${domain}" CDNSKEY "${domain}" CDS | tee "${DSPROCESS_PATH}/${view}/file-${domain}" >/dev/null
+
+exit 0
diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -2,33 +2,76 @@
 # cme-dnssec-monitor/clean v0.1.0
 # removes DS keys from bind
 
-if [[ $# -lt 4 ]]; then
-  echo "cme-dnssec-monitor/clean v0.1.0 - removes DS keys from BIND"
-  echo "  usage: $ clean ${ip_addr} ${ns_server} ${domain} ${ttl} ${view}"
+if [[ $# -gt 6 || $# -lt 5 ]]; then
+  echo -e
+  echo "cme-dnssec-monitor/clean v0.1.0 - updates CDS/DS keys in a zone"
+  echo "$@"
+  echo -e
+  echo "Usage:"
+  echo "  ENV VARS - declare/export these env values and pass \"\" as an empty parameter
+  declare -x DOMAIN=\"example.com\"
+  declare -x VIEW=\"externals-master\"
+  declare -x IP_ADDR=\"127.0.0.1\"
+  declare -x NS_SERVER=\"192.68.0.2\"
+  declare -x TTL=60
+  declare -x KEY_ID=01234
+"
+  echo -e
+
+  echo "  examples:"
+  echo "  $ update \$ip_addr} \$ns_server} \$domain} \$ttl} \$view}"
+  echo -e
+  echo "  $ TTL=60"
+  echo "  $ update 127.0.0.1 192.168.88.2 test.com \"\" externals-master"
   exit 1
 fi
 
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 
-if [[ ${CME_DNSSEC_MONITOR_DEBUG:-notloaded} == "notloaded" || ${CME_DNSSEC_MONITOR_DEBUG:-notloaded} -eq 0 ]]; then
+if [[ -f "/etc/cme/dnssec-monitor.env" ]]; then
   # shellcheck disable=SC1091
   . "/etc/cme/dnssec-monitor.env"
 fi
 
 if [[ -f "${DIR}/lib.sh" ]]; then
   # shellcheck disable=SC1091
+  echo "...loading lib"
   . "${DIR}/lib.sh"
 fi
 
-declare ip_addr=$1
-declare ns_server=$2
-declare domain=$3
-declare ttl=$4
-declare view=$5
-
-declare domain_key
-declare domain_conf
+declare domain="${DOMAIN:-$1}"
+declare view="${VIEW:-$2}"
+declare ip_addr="${IP_ADDR:-$3}"
+declare ns_server="${NS_SERVER:-$4}"
+declare ttl="${TTL:-$5}"
+declare key_id="${KEY_ID:-$6}"
+declare dsprocess_path="${DSPROCESS_PATH:-/tmp/cme/dsprocess}"
+declare domain_key="${CONF_PATH}/rndc.${view}.key"
+declare domain_conf="${CONF_PATH}/rndc.${view}.conf"
 declare domain_parent
+declare record
+
+key_id=$(printf "%05d" "${key_id}")
+declare key_path="${KEY_PATH}/${view}/K${domain}.+014+${key_id}.key"
+domain_parent=$(parent_domain ${domain})
+
+render_params
+
+if [[ ! -f "${domain_key}" ]]; then
+  log "rndc key file not found at ${domain_key}! Aborting"
+  exit 2
+fi
+
+if [[ ! -f "${key_path}" ]]; then
+  log "${key_path} NOT found! Aborting."
+  exit 2
+fi
+
+if [[ ! -d "${dsprocess_path}/${view}" ]]; then
+  mkdir "${dsprocess_path}/${view}"
+fi
+chown root:root "${dsprocess_path}/${view}"
+chmod 770
 
 # shellcheck disable=SC2086,2155
 domain_parent="$(parent_domain $domain)"
@@ -53,7 +96,7 @@ update del ${domain}. DS
 send
 quit
 EOFT
-log "...clean ${domain} DS parent records $(success_icon $?)"
+log "$(success_icon $?)...clean ${domain} DS parent records"
 
 nsupdate -k "${domain_key}" <<EOFT
 server ${ns_server}
@@ -62,7 +105,7 @@ update del ${domain}. CDS
 send
 quit
 EOFT
-log "...clean ${domain} CDS parent records $(success_icon $?)"
+log "$(success_icon $?)...clean ${domain} CDS parent records"
 
 nsupdate -k "${domain_key}" <<EOFT
 server ${ns_server}
@@ -71,7 +114,7 @@ update del ${domain}. DS
 send
 quit
 EOFT
-log "...clean ${domain} DS records $(success_icon $?)"
+log "$(success_icon $?)...clean ${domain} DS records"
 
 nsupdate -k "${domain_key}" <<EOFT
 server ${ns_server}
@@ -82,11 +125,16 @@ quit
 EOFT
 log "...clean ${domain} CDS records$(success_icon $?)"
 
-rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" sync -clean
+rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" sync -clean "${domain}" IN "${view}"
+rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" sync -clean "${domain_parent}" IN "${view}"
 log "$(success_icon $?)...syncing           : all views"
 
 rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" flush "${view}"
 log "$(success_icon $?)...flushing ${view}"
+
+rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" notify "${domain_parent}" IN "${view}"
+rndc -c "${domain_conf}" -k "${domain_key}" -s "${ns_server}" notify "${domain}" IN "${view}"
+log "$(success_icon $?)...notifying ${view}"
 
 # get the records
 readarray -td$'\n' ds_dnskey_records < <(dig -b "${ip_addr}" "@${ns_server}" +norecurse "${domain}". DNSKEY | dnssec-dsfromkey -a SHA-384 -f - "${domain}")
diff --git a/update b/update
--- a/update
+++ b/update
@@ -7,111 +7,125 @@
 # VIEW=externals-master
 # $ update ${domain} ${key_id} ${view}
 
-if [[ $# -lt 4 ]]; then
-  echo "cme-dnssec-monitor/clean v0.1.0 - removes DS keys from BIND"
-  echo "  usage: $ clean ${ip_addr} ${ns_server} ${domain} ${ttl} ${view}"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+
+if [[ $# -lt 6 || $# -gt 6 ]]; then
+  echo "cme-dnssec-monitor/update v0.1.0 - updates CDS/DS keys in a zone"
+  echo "$@"
+  echo -e
+  echo "Usage:"
+  echo "  ENV VARS - declare/export these env values and pass \"\" as an empty parameter
+  declare -x DOMAIN=\"example.com\"
+  declare -x VIEW=\"externals-master\"
+  declare -x IP_ADDR=\"127.0.0.1\"
+  declare -x NS_SERVER=\"192.68.0.2\"
+  declare -x TTL=60
+  declare -x KEY_ID=01234
+"
+  echo -e
+
+  echo "  examples:"
+  echo "  $ update \$domain \$view \$ip_addr \$ns_server \$ttl \$key_id"
+  echo -e
+  echo "  $ TTL=60"
+  echo "  $ add test.example.com externals-master 10.0.254.2 192.168.88.2 "" 01234"
+  exit 1
   exit 1
 fi
 
-DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
-
-if [[ ${CME_DNSSEC_MONITOR_DEBUG:-notloaded} == "notloaded" || ${CME_DNSSEC_MONITOR_DEBUG:-notloaded} -eq 0 ]]; then
+if [[ -f "/etc/cme/dnssec-monitor.env" ]]; then
   # shellcheck disable=SC1091
   . "/etc/cme/dnssec-monitor.env"
 fi
 
 if [[ -f "${DIR}/lib.sh" ]]; then
-  echo "loading lib"
   # shellcheck disable=SC1091
+  echo "...loading lib"
   . "${DIR}/lib.sh"
 fi
 
 declare domain=${DOMAIN:-$1}
-declare key_id=${KEY_ID:-$2}
-declare view=${VIEW:-$3}
-declare dsprocess_path=${DSPROCESS_PATH:-$4}
+declare view=${VIEW:-$2}
+declare ip_addr=${IP_ADDR:-$3}
+declare ns_server=${NS_SERVER:-$4}
+declare ttl=${TTL:-$5}
+declare key_id=${KEY_ID:-$6}
+declare dsprocess_path=${DSPROCESS_PATH:-/tmp/cme/dsprocess}
+declare domain_key=/etc/bind/rndc.${view}.key
+declare domain_conf=/etc/bind/rndc.${view}.conf
 declare domain_parent
-declare ttl=${TTL:$-60}
+declare record
 
 key_id=$(printf "%05d" "${key_id}")
-domain_parent=$(parent_domain "${domain}")
 
-# shellcheck disable=SC2068
-view_var="${view^^}"
-view_var="${view_var//-/_}"
-iface_var=${view_var}_IFACE
-ip_addr="${!iface_var}"
-declare -n ns_server_var="${view_var}_NS_SERVER"
-ns_server="${ns_server_var}"
+declare key_path="${KEY_PATH}/${view}/K${domain}.+014+${key_id}.key"
 
-key_var=${view_var}_KEY_NAME
-key_name="${!key_var}"
-key_name_var="${key_name^^}"
-key_name_var="${key_name_var//-/_}"
-key_file="${CONF_PATH}/rndc.${view}.key"
+domain_parent=$(parent_domain ${domain})
+render_params
 
-log "handling CDS publish"
-log "ns_server............... : ${ns_server}"
-log "view ................... : ${view}"
-log "domain ................. : ${domain}"
-log "key_id ................. : ${key_id}"
-log "key_var ................ : ${!key_var}"
-log "ip_addr ................ : ${ip_addr}"
-log "key_name ............... : ${key_name}"
-log "key_file ................: ${key_file}"
-log "ttl .................... : ${ttl}"
-
-if [[ ! -f "${CONF_PATH}/rndc.${view}.key" ]]; then
-  log "rndc key file not found at ${CONF_PATH}/rndc.${view}.key! Aborting"
-  exit 0
+if [[ ! -f "${domain_key}" ]]; then
+  log "rndc key file not found at ${domain_key}! Aborting"
+  exit 2
 fi
 
-if [[ ! -f "${KEY_PATH}/${view}/K${domain}.+014+${key_id}.key" ]]; then
-  log "key file ${KEY_PATH}/${view}/K${domain}.+014+${key_id}.key NOT found! Aborting."
-  exit 0
+if [[ ! -f "${key_path}" ]]; then
+  log "${key_path} NOT found! Aborting."
+  exit 2
 fi
 
 if [[ ! -d "${dsprocess_path}/${view}" ]]; then
   mkdir "${dsprocess_path}/${view}"
-  chmod 770
-  touch "${dsprocess_path}/${view}/dsset-${view}-${domain}."
-  touch "${dsprocess_path}/${view}/file-${view}-${domain}"
-  touch "${dsprocess_path}/${view}/nsup.${domain}"
 fi
+chown root:root "${dsprocess_path}/${view}"
+chmod 770
 
 log "removing old nsup"
 rm "${dsprocess_path}/${view}/nsup.${domain}"
+
+nsup_file=${dsprocess_path}/${view}/nsup.${domain}
+dsset_file=${dsprocess_path}/${view}/dsset-${view}-${domain}
+cds_file=${dsprocess_path}/${view}/file-${view}-${domain}
+
+touch "${dsset_fileprocess_path}/${view}/dsset-${view}-${domain}."
+touch "${dsprocess_path}/${view}/file-${view}-${domain}"
+touch "${dsprocess_path}/${view}/nsup.${domain}"
+
 mkdir -p "${dsprocess_path}/${view}"
 if [[ ! -f "${dsprocess_path}/${view}/dsset-${domain}." ]]; then
-  echo digging ns_server_var$:ns_server_var
+log "creating dnsec-cds DS dsset file"
   dig -b "${ip_addr}" "@${ns_server}" +norecurse "${domain}". DNSKEY | dnssec-dsfromkey -a SHA-384 -f - "${domain}" | tee "${dsprocess_path}/${view}/dsset-${domain}." >/dev/null
 fi
+log "creating dnsec-cds CDS file"
 dig -b "${ip_addr}" "@${ns_server}" +dnssec +noall +answer "${domain}" DNSKEY "${domain}" CDNSKEY "${domain}" CDS | tee "${dsprocess_path}/${view}/file-${domain}" >/dev/null
 
+log "creating dnsec-cds nsup"
 log "$(dnssec-cds -a SHA-384 -s-86400 -T "${ttl}" -u -i -f "${dsprocess_path}/${view}/file-${domain}" -d "${dsprocess_path}/${view}" -i"orig" "${domain}" | tee "${dsprocess_path}/${view}/nsup.${domain}" >/dev/null)"
 
+log "content dnsec-cds CDS file"
 echo ${dsprocess_path}/${view}/file-${domain}
 cat ${dsprocess_path}/${view}/file-${domain}
-
+log "content dnsec-cds nsup file"
 echo ${dsprocess_path}/${view}/nsup.${domain}
 cat ${dsprocess_path}/${view}/nsup.${domain}
 
 log "thawing ${domain_parent} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" thaw ${domain_parent} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" thaw ${domain_parent} in ${view}
 
 log "$(
   cat <<EOF
-nsupdate -k "${CONF_PATH}/rndc.${view}.key" <<EOFT
+nsupdate -k "${domain_key}" <<EOFT
+local ${ip_addr}
 server ${ns_server}
 zone ${domain_parent}.
-$(cat ${dsprocess_path}/${view}/nsup.${domain})
+$(cat ${nsup_file})
 send
 quit
 )
 EOF
 )"
 
-nsupdate -k "${CONF_PATH}/rndc.${view}.key" <<EOFT
+nsupdate -k "${domain_key}" <<EOFT
+local ${ip_addr}
 server ${ns_server}
 zone ${domain_parent}.
 $(cat ${dsprocess_path}/${view}/nsup.${domain})
@@ -120,20 +134,22 @@ quit
 EOFT
 
 log "freezing ${domain_parent} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" freeze ${domain_parent} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" freeze ${domain_parent} in ${view}
 log "syncing ${domain_parent} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" sync -clean ${domain_parent} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" sync -clean ${domain_parent} in ${view}
 log "thawing ${domain_parent} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" thaw ${domain_parent} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" thaw ${domain_parent} in ${view}
 
 log "freezing ${domain} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" freeze ${domain} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" freeze ${domain} in ${view}
 log "syncing ${domain} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" sync -clean ${domain} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" sync -clean ${domain} in ${view}
 log "thawing ${domain} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" thaw ${domain} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" thaw ${domain} in ${view}
 
 log "notifying ${domain_parent} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" notify ${domain_parent} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" notify ${domain_parent} in ${view}
 log "notifying ${DOMAIN} in ${view}"
-rndc -k "${CONF_PATH}/rndc.${view}.key" -c "${CONF_PATH}/rndc.${view}.conf" notify ${DOMAIN} in ${view}
+rndc -k "${domain_key}" -c "${CONF_PATH}/rndc.${view}.conf" notify ${DOMAIN} in ${view}
+
+exit 0
